### ISSUE TITLE
Issue with using #shutdown as a scheduled task

### ISSUE THREAD

**Issue by cikez** [maca134/MBCon#7]
When I am trying to use #shutdown as a scheduled task I am getting the following error:

Sending Message: Server with automatically restart in 3 minutes.
RCon admin #1: (Global) Server with automatically restart in 3 minutes.
Sending Message: Server with automatically restart in 2 minutes.
RCon admin #1: (Global) Server with automatically restart in 2 minutes.
Sending Message: Server with automatically restart in 1 minute.
Unhandled Exception: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index -    at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at RestartMessages.RestartMessages.TaskMonitor()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
RCon admin #1: (Global) Server with automatically restart in 1 minute.

Here is my Schedule.json:

[
    {
        "start": "10800",
        "interval": "10800",
        "loop": "1",
        "cmd": "#shutdown"
    }
]

Any ideas?

**Comment by cikez** [comment]
I really wish I knew C# .NET, I would gladly fix this myself. Anyone at all know how to fix the errors from ScheduledTasks?

**Comment by cikez** [comment]
I receive this error when trying to do the ScheduledTask "#shutdown" in debug mode.

Config file found, continuing to load...
Loading BEClient...
Loading Plugins...
Plugin BEFilterMonitor loading failed: BEFilterMonitor has been disabled

## Plugin PlayerCheck loading failed: PlayerCheck has been disabled

## Scheduled Tasks

Task 1
Running in about 9 seconds, 896 milliseconds
Command: Shutdown 

Plugin SimpleMessages loading failed: SimpleMessages has been disabled
Plugin WebLogger loading failed: WebLogger has been disabled
Started HTTP server at http://*:8899/. Password: weblog
Connecting to server...
Connected to 127.0.0.1:2302
RCon admin #1 (127.0.0.1:64149) logged in
Running Task: Shutdown 
Unhandled Exception: Object reference not set to an instance of an object. -    at ScheduledTasks.ScheduledTasks.TaskMonitor()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
